version: '3.1'

services:

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: devdojo
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - microservices_devdojo:/var/lib/mysql

volumes:
  microservices_devdojo: